/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chat;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class WebSocketChatApplication {
	public static void main(String[] args) {
		
		SpringApplication.run(WebSocketChatApplication.class , args);
	}
}
